<?php

namespace App\Models;

use App\Models\Scopes\UserScope;
use App\Notifications\ResetPasswordNotification;
use App\Observers\UserObserver;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Hidden;
use Illuminate\Database\Eloquent\Attributes\ObservedBy;
use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Attributes\ScopedBy;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

#[ObservedBy([UserObserver::class])]
#[ScopedBy([UserScope::class])]
#[Fillable(['username', 'email', 'password', 'superadmin'])]
#[Hidden(['password', 'remember_token'])]
class User extends Authenticatable
{
    use HasApiTokens, HasFactory, HasUuids, Notifiable;

    /**
     * Plain-text password generated by UserObserver::creating(), read once by
     * UserObserver::created() to email it. Never persisted — the 'hashed' cast
     * already hashed $password synchronously on assignment.
     */
    public ?string $generatedPassword = null;

    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'superadmin' => 'boolean',
        ];
    }

    #[Scope]
    public function search(Builder $builder, string $search): Builder
    {
        return $builder;
    }

    public function sendPasswordResetNotification(#[\SensitiveParameter] $token): void
    {
        $url = config('app.frontend_url').'/reset-password?token='.$token.'&email='.urlencode($this->email);
        $this->notify(new ResetPasswordNotification($url));
    }
}
